# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build and Publish

on: [ push, pull_request ]

jobs:
  build:
    name: Build modules
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: --stacktrace --info build

      - uses: actions/upload-artifact@v2
        name: Upload Common
        with:
          name: Common
          path: deck-common/build/libs/

      - uses: actions/upload-artifact@v2
        name: Upload Rest
        with:
          name: Rest
          path: deck-rest/build/libs/

      - uses: actions/upload-artifact@v2
        name: Upload Gateway
        with:
          name: Gateway
          path: deck-gateway/build/libs/

      - uses: actions/upload-artifact@v2
        name: Upload Extras
        with:
          name: Gateway
          path: deck-extras/build/libs/