name: Publish

on:
  release:
    types: [created]

jobs:
  publish:
    name: Publish Release Artifacts
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up Java 8 JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
          architecture: x64
          cache: 'gradle'
          check-latest: true

      - name: Decode GPG Key
        run: |
          mkdir -p ~/.gradle/
          echo "${{secrets.SIGNING_KEY}}" > ~/.gradle/secring.gpg.b64
          base64 -d ~/.gradle/secring.gpg.b64 > ~/.gradle/secring.gpg

      - name: Publish package
        run: ./gradlew publish -Psigning.keyId=${{secrets.SIGNING_KEY_ID}} -Psigning.password='${{secrets.SIGNING_SECRET}}' -Psigning.secretKeyRingFile=$(echo ~/.gradle/secring.gpg) --warn --stacktrace
        env:
          NEXUS_USERNAME: ${{secrets.NEXUS_USERNAME}}
          NEXUS_PASSWORD: ${{secrets.NEXUS_PASSWORD}}